// <auto-generated />
namespace W2022_PassionProject.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class pets : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(pets));
        
        string IMigrationMetadata.Id
        {
            get { return "202202161527274_pets"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
